import type { Metadata } from 'next';
import { Vollkorn } from 'next/font/google';
import './global.css';

const vollkorn = Vollkorn({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vollkorn.className}>
        <div className="estrutura">{children}</div>
      </body>
    </html>
  );
}
